/**************************************************************************** 
 * Job:             J1L_MGT_HR_AGE                        A5AL4R67.C600031U * 
 * Description:     Loads the age dimension table                           * 
 *                                                                          * 
 * Metadata Server: SWIDWHMETAD01                                           * 
 * Port:            8561                                                    * 
 * Location:        /DI/Output/MGT/Workforce/HR/Jobs/Data Mart              * 
 *                                                                          * 
 * Server:          SASApp                                A5AL4R67.AS000002 * 
 *                                                                          * 
 * Source Tables:   TU_MGT_HR_AGE_CLASS -                 A5AL4R67.BF000277 * 
 *                   LU5MGTHR.TU_MGT_HR_AGE_CLASS                           * 
 *                  TD_MGT_HR_AGE - LM_HR.TD_MGT_HR_AGE   A5AL4R67.BF00027E * 
 * Target Table:    TD_MGT_HR_AGE - LM_HR.TD_MGT_HR_AGE   A5AL4R67.BF00027E * 
 *                                                                          * 
 * Generated on:    Wednesday, September 3, 2025 at 4:29:16 PM Central      * 
 *                   European Summer Time                                   * 
 * Generated by:    Walid.ElZouiri@MINECO2000                               * 
 * Version:         SAS Data Integration Studio 4.906                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5AL4R67.C600031U);
%let etls_jobName = %nrquote(J1L_MGT_HR_AGE);
%let etls_userID = %nrquote(Walid.ElZouiri@MINECO2000);

%global applName;
data _null_;
applName="SAS Data Integration Studio";
call symput('applName',%nrstr(applName));
run;
/* Performance Statistics require ARM_PROC sub-system   */ 
%macro etls_startPerformanceStats;
   %log4sas();
   %log4sas_logger(Perf.ARM, 'level=info');
   options armagent=log4sas armsubsys=(ARM_PROC);
   %global _armexec;
   %let _armexec = 1;
   %perfinit(applname="&applName");
%mend;
%etls_startPerformanceStats;

%macro etls_setArmagent;
   %let armagentLength = %length(%sysfunc(getoption(armagent)));
   %if (&armagentLength eq 0) %then
      %do;
         %log4sas();
         %log4sas_logger(Perf.ARM, 'level=info');
         options armagent=log4sas armsubsys=(ARM_PROC);
      %end;
%mend etls_setArmagent;

%macro etls_setPerfInit;
   %if "&_perfinit" eq "0" %then 
      %do;
         %etls_setArmagent;
         %global _armexec;
         %let _armexec = 1;
         %perfinit(applname="&applName");
      %end;
%mend etls_setPerfInit; 

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(SASApp);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(swidwhmetad01.internal.economie.fgov.be);

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*==========================================================================* 
 * Step:            Create ages                           A5AL4R67.C8000DHK * 
 * Transform:       User Written                                            * 
 * Description:     from 0 to 150 year                                      * 
 *                                                                          * 
 * Target Table:    User Written Code Target -            A5AL4R67.BU000720 * 
 *                   work.W64RAUSS                                          * 
 *                                                                          * 
 * User Written:    Calculate age class                                     * 
 *==========================================================================*/ 

%let transformID = %quote(A5AL4R67.C8000DHK);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

/* Runtime statistics macros  */ 
%etls_setPerfInit;
%perfstrt(txnname=%BQUOTE(_DISARM|&transformID|&syshostname|UserWritten))   ;

%let _INPUT_count = 0;
%let _OUTPUT_count = 1;
%let _OUTPUT = work.W64RAUSS;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/User Written Code Target_A5AL4R67.BU000720%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = NM_AGE TX_AGE TX_AGE_NL TX_AGE_FR;
%let _OUTPUT_col_count = 4;
%let _OUTPUT_col0_name = NM_AGE;
%let _OUTPUT_col0_table = work.W64RAUSS;
%let _OUTPUT_col0_length = 8;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = ;
%let _OUTPUT_col0_informat = ;
%let _OUTPUT_col0_label = %nrquote(Age);
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input_count = 0;
%let _OUTPUT_col1_name = TX_AGE;
%let _OUTPUT_col1_table = work.W64RAUSS;
%let _OUTPUT_col1_length = 24;
%let _OUTPUT_col1_type = $;
%let _OUTPUT_col1_format = ;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote(Age);
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input_count = 0;
%let _OUTPUT_col2_name = TX_AGE_NL;
%let _OUTPUT_col2_table = work.W64RAUSS;
%let _OUTPUT_col2_length = 24;
%let _OUTPUT_col2_type = $;
%let _OUTPUT_col2_format = ;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote(Leeftijd);
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input_count = 0;
%let _OUTPUT_col3_name = TX_AGE_FR;
%let _OUTPUT_col3_table = work.W64RAUSS;
%let _OUTPUT_col3_length = 24;
%let _OUTPUT_col3_type = $;
%let _OUTPUT_col3_format = ;
%let _OUTPUT_col3_informat = ;
%let _OUTPUT_col3_label = %nrquote(Âge);
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input_count = 0;
%let _OUTPUT_filetype = WorkTable;

%let _OUTPUT1 = work.W64RAUSS;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/User Written Code Target_A5AL4R67.BU000720%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = NM_AGE TX_AGE TX_AGE_NL TX_AGE_FR;
%let _OUTPUT1_col_count = 4;
%let _OUTPUT1_col0_name = NM_AGE;
%let _OUTPUT1_col0_table = work.W64RAUSS;
%let _OUTPUT1_col0_length = 8;
%let _OUTPUT1_col0_type = ;
%let _OUTPUT1_col0_format = ;
%let _OUTPUT1_col0_informat = ;
%let _OUTPUT1_col0_label = %nrquote(Age);
%let _OUTPUT1_col0_exp = ;
%let _OUTPUT1_col0_input_count = 0;
%let _OUTPUT1_col1_name = TX_AGE;
%let _OUTPUT1_col1_table = work.W64RAUSS;
%let _OUTPUT1_col1_length = 24;
%let _OUTPUT1_col1_type = $;
%let _OUTPUT1_col1_format = ;
%let _OUTPUT1_col1_informat = ;
%let _OUTPUT1_col1_label = %nrquote(Age);
%let _OUTPUT1_col1_exp = ;
%let _OUTPUT1_col1_input_count = 0;
%let _OUTPUT1_col2_name = TX_AGE_NL;
%let _OUTPUT1_col2_table = work.W64RAUSS;
%let _OUTPUT1_col2_length = 24;
%let _OUTPUT1_col2_type = $;
%let _OUTPUT1_col2_format = ;
%let _OUTPUT1_col2_informat = ;
%let _OUTPUT1_col2_label = %nrquote(Leeftijd);
%let _OUTPUT1_col2_exp = ;
%let _OUTPUT1_col2_input_count = 0;
%let _OUTPUT1_col3_name = TX_AGE_FR;
%let _OUTPUT1_col3_table = work.W64RAUSS;
%let _OUTPUT1_col3_length = 24;
%let _OUTPUT1_col3_type = $;
%let _OUTPUT1_col3_format = ;
%let _OUTPUT1_col3_informat = ;
%let _OUTPUT1_col3_label = %nrquote(Âge);
%let _OUTPUT1_col3_exp = ;
%let _OUTPUT1_col3_input_count = 0;
%let _OUTPUT1_filetype = WorkTable;

/*---- Start of User Written Code  ----*/ 

data &_output;
 do NM_AGE = 0 to 150;
	TX_AGE = put(NM_AGE,8.-L);
	TX_AGE_FR = TX_AGE;
	TX_AGE_NL = TX_AGE;
	output;
 end;
run;

/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%perfstop;



/** Step end Create ages **/

/*==========================================================================* 
 * Step:            Inner Join                            A5AL4R67.C8000DHL * 
 * Transform:       Join                                                    * 
 * Description:     add age classes                                         * 
 *                                                                          * 
 * Source Tables:   User Written Code Target -            A5AL4R67.BU000720 * 
 *                   work.W64RAUSS                                          * 
 *                  TU_MGT_HR_AGE_CLASS -                 A5AL4R67.BF000277 * 
 *                   LU5MGTHR.TU_MGT_HR_AGE_CLASS                           * 
 * Target Table:    Join - work.W1DRZ6I                   A5AL4R67.BU000721 * 
 *==========================================================================*/ 

%let transformID = %quote(A5AL4R67.C8000DHL);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

/* Access the data for LU5_MGT_HR  */ 
LIBNAME LU5MGTHR BASE "E:\Data\Libraries\LU5_MGT_HR";
%rcSet(&syslibrc); 

/* Runtime statistics macros  */ 
%etls_setPerfInit;
%perfstrt(txnname=%BQUOTE(_DISARM|&transformID|&syshostname|SQLJoin))   ;

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W1DRZ6I;
quit;

proc sql;
   create view work.W1DRZ6I as
   select
      W64RAUSS.NM_AGE length = 8   
         label = 'Age',
      W64RAUSS.TX_AGE length = 24   
         label = 'Age',
      W64RAUSS.TX_AGE_NL length = 24   
         label = 'Leeftijd',
      W64RAUSS.TX_AGE_FR length = 24   
         label = 'Âge',
      ifc(TU_MGT_HR_AGE_CLASS.NM_AGE_MAX < 150,
      	catx('-',put(TU_MGT_HR_AGE_CLASS.NM_AGE_MIN,8.),put(TU_MGT_HR_AGE_CLASS.NM_AGE_MAX,8.)),
      	cats(TU_MGT_HR_AGE_CLASS.NM_AGE_MIN,'+')
      ) as TX_AGE_CLASS length = 24   
         label = 'Age Class',
      ifc(TU_MGT_HR_AGE_CLASS.NM_AGE_MAX < 150, 
      	catx(' ',put(TU_MGT_HR_AGE_CLASS.NM_AGE_MIN,8.),'t.e.m.',put(TU_MGT_HR_AGE_CLASS.NM_AGE_MAX,8.),'jaar'), 
      	catx(' ',put(TU_MGT_HR_AGE_CLASS.NM_AGE_MIN,8.),'jaar of ouder') 
      ) as TX_AGE_CLASS_DESCR_NL length = 24   
         label = 'Leeftijdsklasse',
      ifc(TU_MGT_HR_AGE_CLASS.NM_AGE_MAX < 150,
      	catx(' ',put(TU_MGT_HR_AGE_CLASS.NM_AGE_MIN,8.),'à',put(TU_MGT_HR_AGE_CLASS.NM_AGE_MAX,8.),'ans'),
      	catx(' ',put(TU_MGT_HR_AGE_CLASS.NM_AGE_MIN,8.),'ans ou plus')
      ) as TX_AGE_CLASS_DESCR_FR length = 24   
         label = 'Classe d''âge'
   from
      work.W64RAUSS as W64RAUSS inner join 
      LU5MGTHR.TU_MGT_HR_AGE_CLASS as TU_MGT_HR_AGE_CLASS
         on
         (
            W64RAUSS.NM_AGE BETWEEN TU_MGT_HR_AGE_CLASS.NM_AGE_MIN and  TU_MGT_HR_AGE_CLASS.NM_AGE_MAX
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 

%perfstop;



/** Step end Inner Join **/

/*==========================================================================* 
 * Step:            Surrogate Key Generator               A5AL4R67.C8000DHM * 
 * Transform:       Surrogate Key Generator                                 * 
 * Description:     Generates a unique key value for a set of business key  * 
 *                   values.                                                * 
 *                                                                          * 
 * Source Table:    Join - work.W1DRZ6I                   A5AL4R67.BU000721 * 
 * Target Table:    Surrogate Key Generator -             A5AL4R67.BU000722 * 
 *                   work.W64RAV7E                                          * 
 *==========================================================================*/ 

%let transformID = %quote(A5AL4R67.C8000DHM);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W1DRZ6I); 

/* Runtime statistics macros  */ 
%etls_setPerfInit;
%perfstrt(txnname=%BQUOTE(_DISARM|&transformID|&syshostname|GeneratedTransform))   ;

%let _INPUT_count = 1; 
%let _INPUT = work.W1DRZ6I;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Join_A5AL4R67.BU000721%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.W64RAV7E;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/Surrogate Key Generator_A5AL4R67.BU000722%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = ID_AGE NM_AGE TX_AGE TX_AGE_NL TX_AGE_FR TX_AGE_CLASS 
        TX_AGE_CLASS_DESCR_NL TX_AGE_CLASS_DESCR_FR;


%let etls_surrKeyAssignMethod = %nrquote(etls_surrKeyFromTgt);
%let etls_startingSurrKey = %nrquote(1);
%let etls_surrKeyLookupTable = ;
%let etls_surrKeyLookupTable_connect = ;
%let etls_surrKeyLookupTable_engine = ;
%let etls_surrKeyLookupTable_memtype = ;
%let etls_surrKeyLookupTable_options = %nrquote();
%let etls_surrKeyLookupTable_alter = %nrquote();
%let etls_surrKeyLookupTable_path = ;
%let etls_surrKeyLookupTable_type = 1;
%let etls_surrKeyLookupTable_label = %nrquote();
%let etls_surrKeyLookupColumn = ;
%let etls_updateSurrKeyLookupTable = %nrquote(Yes);
%let etls_newOrExistingKeys = %nrquote(etls_genForNew);
%let etls_keepWhichRecords = %nrquote(etls_keepInputRecords);
%let updateSource = %nrquote(NO);
%let etls_force = %nrquote(No);
%let etls_outputTableOptions = ;
%let etls_bulkloadOrInsertbuff = ;
%let etls_insertBuffSize = ;
/* Access the data for LM21_MGT_HR  */ 
LIBNAME LM_HR BASE "E:\Data\Libraries\LM21_MGT_HR";
%rcSet(&syslibrc); 

%let etls_targetTable = LM_HR.TD_MGT_HR_AGE;
%let etls_targetTable_connect = null;
%let etls_targetTable_engine = BASE;
%let etls_targetTable_memtype = DATA;
%let etls_targetTable_options = %nrquote();
%let etls_targetTable_alter = %nrquote();
%let etls_targetTable_path = %nrquote(/EDW/Output/MGT/Workforce/HR/Personal data with direct identifier/Tables/Data Mart/TD_MGT_HR_AGE%(Table%));
%let etls_targetTable_type = 1;
%let etls_targetTable_label = %nrquote(Age dimension table);
%let businessKey = NM_AGE;
%let businessKey_count = 1;
%let businessKey0 = 1;
%let businessKey1 = NM_AGE;
%let surrogateKey = ID_AGE;
%let surrogateKey_count = 1;
%let surrogateKey0 = 1;
%let surrogateKey1 = ID_AGE;
%let targetTable = %nrquote(LM_HRM.TD_MGT_EHRM_AGE);
%let options = ;

/* List of target columns to keep  */ 
%let _keep = ID_AGE NM_AGE TX_AGE TX_AGE_NL TX_AGE_FR TX_AGE_CLASS 
        TX_AGE_CLASS_DESCR_NL TX_AGE_CLASS_DESCR_FR;
/* List of target columns to keep  */ 
%let keep = ID_AGE NM_AGE TX_AGE TX_AGE_NL TX_AGE_FR TX_AGE_CLASS 
        TX_AGE_CLASS_DESCR_NL TX_AGE_CLASS_DESCR_FR;
%macro createSurrogateKey;

%local etls_maxkey;

 options mprint;

 %if (%nrquote(&options) ne) %then
 %do;
    options &options;
 %end; 

 %if (%nrquote(&etls_targetTable) ne ) %then
 %do;
    %let targetTable = &etls_targetTable; 
 %end;


 /* If generating a new surrogate key only for new records not represented in target, or generating */
 /* the key value from target table, or keeping records from target in output, then target table is */
 /* required.    */
 %if (&etls_newOrExistingKeys   = etls_genForNew or
      &etls_surrKeyAssignMethod = etls_surrKeyFromTgt) %then
 %do;
    %if (%nrquote(&targetTable) eq) %then 
    %do;
       %put ERROR: Missing Target Table Option;
       %let sysrc=8000;
       %goto out;
    %end;
 %end;   

 %if (%nrquote(&surrogateKey) eq) %then 
 %do;
    %put ERROR: Missing Surrogate Key Column Option;
    %let sysrc=8000;
    %goto out;
 %end;

 %if (%nrquote(&businessKey) eq) %then 
 %do;
    %put ERROR: Missing Business Key Column Option;
    %let sysrc=8000;
    %goto out;
 %end;
 
 %let tsyslast = &_INPUT (&_INPUT_options);
      
 /* If merge will need to be done, sort input table */
 %if %upcase(&etls_newOrExistingKeys) = ETLS_GENFORNEW %then
 %do;    
    /* determine member type of source table, can not sort Views */
    %let updateSource = %upcase(%nrquote(&updateSource));
    %if (%nrquote(&_INPUT_memtype) eq DATA and (%upcase(&updateSource) eq YES)) %then
       %let updateSource = Y;
    %else
       %let updateSource = N;
   
    proc sort data = &tsyslast 
       %if (&updateSource eq N) %then
       %do; /* %if - the source cannot be updated - save to a temp table */
          out = work.etls_sortedSource
          %let tsyslast = work.etls_sortedSource; 
       %end; /* %if - the source cannot be updated */ 
       %if (%upcase(&etls_force = YES)) %then 
       %do;
         force
       %end;  
    ;
    by &businesskey;
    run;
 %end;   

  
 /* Assign maxKey to be last surrogate key value assigned, or one less than what next value should be. */
 
 %if &etls_surrKeyAssignMethod = etls_surrKeyFromValue %then
    %let etls_maxKey = %eval(&etls_startingSurrKey - 1); 
 %else %if &etls_surrKeyAssignMethod = etls_surrKeyFromLookupTable %then
 %do;  /* Lookup last surrogate key value from lookup table */
    %if (&etls_surrKeyLookupColumn eq) %then
       %let etls_surrKeyLookupColumn = &surrogateKey;
    proc sql noprint;
       select compress(put(&etls_surrKeyLookupColumn, best32.)) into :etls_maxKey 
       from &etls_surrKeyLookupTable (&etls_surrKeyLookupTable_options);
    quit;
    %if &syserr gt 0 and &syserr ne 4 %then %do;
       %rcset(&syserr);
       %put ERROR: Lookup failed to get last surrogate key value from column: &etls_surrKeyLookupColumn  in lookup table: &etls_surrKeyLookupTable;
       %goto out;
    %end;   
 %end; 
 
 %else %do;  /* set maxKey to highest surrogate key value in target table*/  
    %if (%quote(&targetTable) ne and %sysfunc(exist(&targetTable)) eq 1) %then 
    %do;  /* If physical target table exists, look up maximum surrogate key value assigned */  
       proc sql noprint;
          select compress(put(max(&surrogateKey), best32.)) into :etls_maxKey 
          from &targetTable;
       quit;
       %if &syserr gt 0 and &syserr ne 4 %then %do;
          %rcset(&syserr);
          %put ERROR: Failed to get highest surrogate key value from column: &surrogateKey  in table: &targetTable;
          %goto out;
       %end;
    %end;   
 %end;      
       
 %if (&etls_maxkey eq . or &etls_maxkey eq) %then 
    %let etls_maxkey = 0;


 
 /* If merge will need to be done, sort target table and merge with source table if target table exists. */
 /* Replace output table */
 %if (&etls_newOrExistingKeys = etls_genForNew and %sysfunc(exist(&targetTable)) eq 1) %then  
 %do;
    proc sort data=&targetTable out = work.etls_targetSorted;
       by &businesskey;
       run;
    %if &syserr gt 0 and &syserr ne 4 %then %do;
          %rcset(&syserr);
          %put ERROR: &syserr. Sort of &targetTable  failed, so it will not be replaced;
          %goto out;
    %end;   
       
     /* Delete output table if it exists. It can only be replaced. */
    %if (%sysfunc(exist(&_output)) eq 1) %then 
    %do;
       proc datasets lib = %scan(&_output,1,.) nolist nowarn memtype = (data view);
          delete %scan(&_output,2,.) 
			 %if (&_output_alter ne ) %then
			    (&_OUTPUT_alter);
		    ;
       quit;
    %end;

    data &_output
    %if (&_OUTPUT_options ne or &etls_bulkloadOrInsertbuff ne or %nrquote(&etls_outputTableOptions) ne) %then 
    %do;
       (
       %if %upcase(&etls_bulkloadOrInsertbuff) = ETLS_BULKOAD %then
       %do;
          bulkload = yes
       %end;
       %else %if (%upcase(&etls_bulkloadOrInsertbuff) = ETLS_INSERTBUFF and &etls_insertBuffSize ne) %then
       %do; 
          insertbuff = %nrquote(&etls_insertBuffSize)
       %end;
       %if (%nrquote(&etls_outputTableOptions) ne ) %then %do;
          %nrquote(&etls_outputTableOptions)
       %end;   
		 &_OUTPUT_options
       )
    %end;
    ;  /* (end of data statement */
          
     merge work.etls_targetSorted(in = etls_inTarget)
             &tsyslast 
     %if &etls_keepWhichRecords = etls_keepInputRecords %then
     %do;
       (in = etls_inSource)
     %end;  
     %if (%upcase(&etls_updateSurrKeyLookupTable) = YES) %then
     %do; 
       end=etls_lastRecord
     %end;
          ;
     by &businesskey;
     retain etls_newkey &etls_maxkey;
     drop etls_newkey  etls_inTarget ;
     %if &etls_keepWhichRecords = etls_keepInputRecords %then
     %do;
	drop etls_inSource;
     %end;
     %if (%upcase(&etls_updateSurrKeyLookupTable) = YES) %then
     %do; 
	drop etls_lastRecord;
     %end;
          
          
        /* If just keeping input records, then when a record is read that is not in input table, return */
	/* without saving the record. */
     if not etls_inTarget then
     do;
        etls_newkey + 1;
        &surrogatekey = etls_newkey;
     end;
     %if (%upcase(&etls_updateSurrKeyLookupTable) = YES) %then
     %do; 
        if etls_lastRecord then call symput('etls_maxkey', trim(left(put(etls_newkey,15.))));
     %end; 
     %if &etls_keepWhichRecords = etls_keepInputRecords %then
     %do;
	if etls_inSource then output;
     %end; 
         
     run;

     proc datasets lib = work nolist nowarn memtype=(data view);
          delete etls_targetSorted;
     quit;
       
     %if (%upcase(&updateSource) eq N) %then
     %do; /* %if - can not update the source table */
        proc datasets lib = work nolist;
             delete etls_sortedSource;
        quit;
     %end; /* %if - can not update the source table */

 %end; 
 
 %else 
 %do; /* %else - generate a new value for all source records and replace output table */
    /* Delete output table if it exists. It can only be replaced. */
    %if (%sysfunc(exist(&_output)) eq 1) %then 
    %do;
       proc datasets lib = %scan(&_output,1,.) nolist nowarn memtype = (data view);
          delete %scan(&_output,2,.) 
			 %if (&_output_alter ne ) %then
     		    (&_OUTPUT_alter);
  	       ;
       quit;
    %end;
    
    data &_output 
    %if (&_OUTPUT_options ne or &etls_bulkloadOrInsertbuff ne or %nrquote(&etls_outputTableOptions) ne ) %then
    %do;
       (
       %if (&etls_bulkloadOrInsertbuff ne or %nrquote(&etls_outputTableOptions) ne) %then 
       %do;
          %if %upcase(&etls_bulkloadOrInsertbuff) = ETLS_BULKOAD %then
          %do;
             bulkload=yes
          %end;
          %else %if (%upcase(&etls_bulkloadOrInsertbuff) = ETLS_INSERTBUFF and &etls_insertBuffSize ne) %then
          %do; 
             insertbuff=%nrquote(&etls_insertBuffSize)
          %end;
          %if (%nrquote(&etls_outputTableOptions) ne) %then %do;
             %nrquote(&etls_outputTableOptions)
          %end;  
       %end;
	    &_OUTPUT_options
       )  
    %end;
    ;  /* End data statement */
       
    %if (%upcase(&etls_updateSurrKeyLookupTable) = YES) %then
    %do; 
       set &tsyslast end=etls_endOfSource; 
       drop etls_endOfSource;
    %end;
    %else %do;
       set &tsyslast;
    %end;   
    retain &surrogateKey &etls_maxKey;
    &surrogateKey + 1;
    %if (%upcase(&etls_updateSurrKeyLookupTable) = YES) %then
    %do;
       if etls_endOfSource then call symput('etls_maxkey', trim(left(put(&surrogateKey,15.))));
    %end;   
    run; 
 %end; 
 
 %if (%upcase(&etls_updateSurrKeyLookupTable) = YES and &etls_surrKeyAssignMethod = etls_surrKeyFromLookupTable) 
 %then  %do; 
    proc sql;
       update &etls_surrKeyLookupTable (&etls_surrKeyLookupTable_options)
       set &etls_surrKeyLookupColumn = &etls_maxkey;
    quit;
 %end;   
 
 %out:
 %RCSET(&syserr);
%mend;

%createSurrogateKey;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

%perfstop;



/** Step end Surrogate Key Generator **/

/*==========================================================================* 
 * Step:            Table Loader: replace                 A5AL4R67.C8000DHN * 
 * Transform:       Table Loader (Version 2.1)                              * 
 * Description:     + add 'Not available' (-1) & 'Unknown' (-2)             * 
 *                                                                          * 
 * Source Table:    Surrogate Key Generator -             A5AL4R67.BU000722 * 
 *                   work.W64RAV7E                                          * 
 * Target Table:    TD_MGT_HR_AGE - LM_HR.TD_MGT_HR_AGE   A5AL4R67.BF00027E * 
 *==========================================================================*/ 

%let transformID = %quote(A5AL4R67.C8000DHN);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W64RAV7E); 

/* Runtime statistics macros  */ 
%etls_setPerfInit;
%perfstrt(txnname=%BQUOTE(_DISARM|&transformID|&syshostname|Loader))   ;

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

%global etls_tableExist;
%global etls_numIndex;
%global etls_lastTable;
%let etls_tableExist = -1; 
%let etls_numIndex = -1; 
%let etls_lastTable = &SYSLAST; 

/*---- Define load data macro  ----*/ 

/* --------------------------------------------------------------
   Load Technique Selection: Replace - EntireTable
   Constraint and index action selections: 'ASIS','ASIS','ASIS','ASIS'
   Additional options selections... 
      Set unmapped to missing on updates: true 
   -------------------------------------------------------------- */
%macro etls_loader;

   %let etls_tableOptions = ;
   
   /* Determine if the target table exists  */ 
   %let etls_tableExist = %eval(%sysfunc(exist(LM_HR.TD_MGT_HR_AGE, DATA)) or 
         %sysfunc(exist(LM_HR.TD_MGT_HR_AGE, VIEW))); 
   
   %if &etls_tableExist %then 
   %do;/* table exists  */ 
      %let etls_hasPreExistingConstraint=0; 
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_commands etls_commands_F;
      quit;
      
      %let etls_otherTablesReferToThisTable=0;
      
      %macro etls_CIContents(table=,workTableOut=,inDSOptions=);
         %put NOTE: Building table listing Constraints and Indexes for: &table;
         proc datasets lib=work nolist; delete &workTableOut; quit;
         proc contents data=&table&inDSOptions out2=&workTableOut noprint; run;
         
         %if %sysfunc(exist(&workTableOut)) ne 0 %then %do;
            %let _etlsDsid = %sysfunc(open(&workTableOut));
            %let _etlsVarnum = %sysfunc(varnum(&_etlsDsid,RECREATE));
            %if &_etlsVarnum > 0 %then %do;
               %let _etlsRecreateLen = %sysfunc(varlen(&_etlsDsid,&_etlsVarnum)); /* variable length */
            %end;
            %else %let _etlsRecreateLen=5000;
            %let rc = %sysfunc(close(&_etlsDsid));
         %end;
         %else %let _etlsRecreateLen=5000; /* Set a default of 5000 for length if the retrieval is not successful */
         
         data &workTableOut;
            length name $60 type $20 icown idxUnique idxNoMiss $3 recreate $&_etlsRecreateLen;
            name = '';
            type = '';
            icown = '';
            idxUnique = '';
            idxNoMiss = '';
            recreate = '';
            set &workTableOut;
            ref = '';
            type=upcase(type);
            if type eq 'REFERENTIAL' then
            do;
               put "WARNING%QUOTE(:) Target table is referenced by constraints in"
                    " another table: " ref;
               call symput('etls_otherTablesReferToThisTable','1');
               delete;
            end;
            if type='INDEX' and ICOwn eq 'YES' then delete;
         run;
         %rcSet(&syserr); 
         
      %mend etls_CIContents;
      
      %etls_CIContents(table=LM_HR.TD_MGT_HR_AGE, workTableOut=etls_commands, inDSOptions=);
      
      %if &etls_otherTablesReferToThisTable %then 
         %put WARNING%QUOTE(:) Replacing entire table will fail. Consider an alternate load technique or revising constraints.; 
      %else 
      %do; /* okay - remove foreign keys  */ 
      
         data etls_commands_F; 
            set etls_commands; 
            if upcase(type)="FOREIGN KEY" then 
            do; 
               command='ic delete '||trim(name)||';';
               output etls_commands_F; 
            end; 
         run; 
         
         %put %str(NOTE: Removing foreign keys before dropping table...);
         data _null_;
            set etls_commands_F end=eof;
            if _n_=1 then 
               call execute('proc datasets nolist lib=LM_HR;modify TD_MGT_HR_AGE;');
            call execute(command);
            if eof then call execute('; quit;');
         run;
         %rcSet(&syserr); 
         
   %end; /* okay - remove foreign keys  */ 
   
   proc datasets lib = work nolist nowarn memtype = (data view);
      delete etls_commands etls_commands_F;
   quit;
   
   /*---- Drop a table  ----*/ 
   %put %str(NOTE: Dropping table ...);
   proc datasets lib = LM_HR nolist nowarn memtype = (data view);
      delete TD_MGT_HR_AGE;
   quit;
   
   %rcSet(&syserr); 
   
   %let etls_tableExist = 0;
   
%end; /* table exists  */ 

/*---- Create a new table  ----*/ 
%if (&etls_tableExist eq 0) %then 
%do;  /* if table does not exist  */ 

   %put %str(NOTE: Creating table ...);
   
   data LM_HR.TD_MGT_HR_AGE
           (label = 'Age dimension table');
      attrib ID_AGE length = 8
         label = 'Age dimension id'; 
      attrib NM_AGE length = 8
         label = 'Age'; 
      attrib TX_AGE length = $24
         label = 'Age'; 
      attrib TX_AGE_NL length = $24
         label = 'Leeftijd'; 
      attrib TX_AGE_FR length = $24
         label = 'Âge'; 
      attrib TX_AGE_CLASS length = $24
         label = 'Age Class'; 
      attrib TX_AGE_CLASS_DESCR_NL length = $24
         label = 'Leeftijdsklasse'; 
      attrib TX_AGE_CLASS_DESCR_FR length = $24
         label = 'Classe d''âge'; 
      call missing(of _all_);
      stop;
   run;
   
   %rcSet(&syserr); 
   
%end;  /* if table does not exist  */ 

/*---- Append  ----*/ 
%put %str(NOTE: Appending data ...);

proc append base = LM_HR.TD_MGT_HR_AGE 
   data = &etls_lastTable (&etls_tableOptions)  force ; 
 run; 

%rcSet(&syserr); 

%mend etls_loader;
%etls_loader;

/*---- Start of Post-Process Code  ----*/ 

proc sql;
delete * from &SYSLAST
where ID_AGE IN (-1, -2);
quit;

proc sql;
insert into &SYSLAST (
ID_AGE,
TX_AGE,
TX_AGE_NL,
TX_AGE_FR,
TX_AGE_CLASS,
TX_AGE_CLASS_DESCR_NL,
TX_AGE_CLASS_DESCR_FR)
values (
-1, 
"Not available",
"Niet beschikbaar",
"Non disponible",
"Not available",
"Niet beschikbaar",
"Non disponible"
);
quit;

proc sql;
insert into &SYSLAST (
ID_AGE,
TX_AGE,
TX_AGE_NL,
TX_AGE_FR,
TX_AGE_CLASS,
TX_AGE_CLASS_DESCR_NL,
TX_AGE_CLASS_DESCR_FR)
values (
-2, 
"Unknown",
"Onbekend",
"Inconnu",
"Unknown",
"Onbekend",
"Inconnu"
);
quit;

/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

%perfstop;



/** Step end Table Loader: replace **/

/*==========================================================================* 
 * Step:            Export to Excel                       A5AL4R67.C8000DHO * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    TD_MGT_HR_AGE - LM_HR.TD_MGT_HR_AGE   A5AL4R67.BF00027E * 
 * Target Table:    User Written - work.W4J1BF6           A5AL4R67.BU0007B3 * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A5AL4R67.C8000DHO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(LM_HR.TD_MGT_HR_AGE); 

/* Runtime statistics macros  */ 
%etls_setPerfInit;
%perfstrt(txnname=%BQUOTE(_DISARM|&transformID|&syshostname|UserWritten))   ;

%let _INPUT_count = 1;
%let _INPUT = LM_HR.TD_MGT_HR_AGE;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/EDW/Output/MGT/Workforce/HR/Personal data with direct identifier/Tables/Data Mart/TD_MGT_HR_AGE%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Age dimension table);
%let _INPUT_filetype = PhysicalTable;

%let _INPUT1 = LM_HR.TD_MGT_HR_AGE;
%let _INPUT1_connect = null;
%let _INPUT1_engine = BASE;
%let _INPUT1_memtype = DATA;
%let _INPUT1_options = %nrquote();
%let _INPUT1_alter = %nrquote();
%let _INPUT1_path = %nrquote(/EDW/Output/MGT/Workforce/HR/Personal data with direct identifier/Tables/Data Mart/TD_MGT_HR_AGE%(Table%));
%let _INPUT1_type = 1;
%let _INPUT1_label = %nrquote(Age dimension table);
%let _INPUT1_filetype = PhysicalTable;

%let _OUTPUT_count = 1;
%let _OUTPUT = work.W4J1BF6;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/User Written_A5AL4R67.BU0007B3%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
%let _OUTPUT_col_count = 0;
%let _OUTPUT_filetype = WorkTable;

%let _OUTPUT1 = work.W4J1BF6;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/User Written_A5AL4R67.BU0007B3%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
%let _OUTPUT1_col_count = 0;
%let _OUTPUT1_filetype = WorkTable;

/*---- Start of User Written Code  ----*/ 


proc export
	data=&_INPUT (drop= TX_AGE TX_AGE_CLASS)
	dbms=xlsx
	label
	outfile="E:\Data\Output\BI\PowerBI\HR\TD_AGE.xlsx"
	replace;
run;
/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 
%perfstop;



/** Step end Export to Excel **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/* Turn off performance statistics collection  */ 
data _null_;
   if "&_perfinit" eq "1" then 
      call execute('%perfend;');
      
run;